### ISSUE TITLE
Mutation, Crossover or Selection Maybe Off?

### ISSUE THREAD

**Issue by davecom** [terrafirma9/ff_challenge#1]
This is cool. 

When I ran it, I noticed that average fitness sometimes falls way out of range of best fitness and then climbs back up. This likely due to overly aggressive changes in mutation & crossover or incorrect selection. For example, if average fitness has been around -460 for the past few generations, it shouldn't suddenly go to -1600 unless:
A) Mutation or Crossover led to some terrible individuals in the new batch (too much mutation/bad types of mutations allowed, leading to a -300,000 individual that throws off the average).
B) Selection is not consistently selecting better individuals on average. I think this is less likely because after it oscillates back to a poor fitness, it gradually climbs back up in the right direction.

If it's A, perhaps it's not obvious how to do it better, which is fine I guess since it works. I'm just curious if you had any thoughts. Also, did you try a lower mutation rate? .3 is pretty high.

For the repository, you should add a license to your code so other people know how they can reuse it and a description of the original problem so they know why it's useful. Sorry if this sounds overly pedantic, just trying to help.

Best, Dave

**Comment by terrafirma9** [comment]
Hey Dave,

Thanks for the feedback, I appreciate it! I actually build this for a coding challenge that required putting it in a public repo, but yes I should drop in a license. It needs to stay frozen for the next stage of the interview process, but will modify after that. 

I set mutation levels high (both % population that mutates and % of mutations) in hopes new contenders would emerge, but didn't see that happen often, so can probably lower.

The crossover code is the weakest part, because it was hard for me to understand what it meant for two sets of paths to have a child together, and I was trying to get this done by the deadline. 😅 In a refactor I think the Path class should go away, so that paths are just arrays of Locations, which would make it easier to try various 'flavors' of cross.

Also, I want to flesh out my public repos as social proof for future interviews, and was thinking of leaving this up with improvements and modifications (support for N drivers instead of two, CSV support, GUI to modify and etc). If I do that, do you want me to link to a page for your book, or your website? Let me know - I'm happy to add that.

Matthew

**Comment by davecom** [comment]
Hey Matthew,

I think that's awesome. Yeah, if you want to put a [link to the book](https://www.manning.com/books/classic-computer-science-problems-in-swift), that would be cool, but you don't have to. I think your solution for crossover (using an array of Locations) would be really nice and would simplify things well. Anytime you publish any code publicly  on line you should put a license, just because otherwise it makes it ambiguous for other people. You retain the full copyright if you don't put a license, but then other people who see it are like "Wait did the person mean not to put a license? Can I actually reuse this?"

Anyway, this was cool to come across. Best of luck with the coding challenge.
Best,
Dave

PS Thanks for buying the book!
